### ISSUE TITLE
Show human readable count on download button

### ISSUE THREAD

**Issue by psachin** [psachin/haqiba#11]
The button length increases when the 'download_count' increase. We need to come up with a solution that will convert the 'counts' to human readable format.

Like:

1000 => 1K
1500 => 1.5K
10000 => 10K
.
.
100000 => 1000K
.
.
1000000 => M

and so on.

**Comment by psachin** [comment]
def size_suffix(size):
    suffixes = ['bytes', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
    for suffix in suffixes:
        if size < 1000:
            return "%s %s" % (size, suffix)
        size = size // 1000
    return "%s %s" % (size, suffix)

**Comment by nutannivate** [comment]
Kya karna hai?
